name: Generate and publish API JavaDocs
on:
  push:
    branches:
      - main-test
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

    - name: Generate docs
      run: mvn javadoc:javadoc

    - name: Print runner directory
      run: |
        echo "Runner directory: ${{ github.workspace }}"

    - name: List directory structure
      run: find ${{ github.workspace }}

    - name: Upload docs artifact
      uses: actions/upload-artifact@v3
      with:
        name: javadocs
        path: ./target/report/apidocs

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/report/apidocs
